version: '3'

services:
    app:
        build: .
        volumes:
            - .:/usr/src/app
        command: npm run prod
        environment:
            - DATABASE_HOST=db
            - DATABASE_PORT=5432
            - DATABASE_USER=postgres
            - DATABASE_PASSWORD=${POSTGRES_PASSWORD}
            - DATABASE_NAME=${POSTGRES_DB}
        depends_on:
            - db

    db:
        image: postgres:latest
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
        volumes:
            - pgdata:/var/lib/postgresql/data
        ports:
            - '5432:5432'

volumes:
    pgdata:
